var shouldOptions = 
["become a rockstar?",
"buy a ticket to your show?",
"recite a Shakespeare sonet?",
"move Louvre to the British Museum?",
"dedicate my life to quantum physics?", 
"fight a ghost?", 
"become a chess grandmaster?", 
"destroy the universe?", 
"chop down a tree?", 
"add pineapple on pizza?", 
"chase a dragon?", 
"become a kung fu fighter?", 
"write a Broadway musical?",  
"get myself a cockatoo?", 
"invent teleportation?", 
"study the Ancient Greek philosophers?", 
"take up Mongolian throat singing?", 
"make outdated pop culture references?",
"steal code from StackOverflow?",
"go sleep?", 
"contemplate the vastness of the universe?", 
"become a farmer?", 
"build up my cinematic universe?", 
"write a game engine from scratch?", 
"pursue an academic career?", 
"delete the internet?", 
"make exaggerated predictions about the year 3000?", 
"download some open source software?",  
"make a disco beat?", 
"build a dog house?", 
"revisit classic cat videos from 2008?", 
"start working on my stand-up comedy special?", 
"confuse myself and be mad?", 
"go out fishing in a river or a creek?",
"pack my bags and go to New York City?", 
"randomly crash a spaceship?", 
"ride a horse and regret it?", 
"audition for Tom's Music School?", 
"speedrun Super Archie?", 
"finally upgrade to Windows XP?", 
"worry about my troubles?", 
"stop overworking my pet hamster?", 
"be at the forefront of a major economic scandal?",  
"question my senses?", 
"laugh or should I cry?", 
"stay or should I go?", 
"accumulate a substantial amount of wealth?", 
"appear on a pseudo-scientific TV panel?", 
"beg my landlord to forgive me?",
"breathe the fresh air from my balconi in Verona?", 
"pour milk before the cereal?", 
"campaign for Mayor of Clownville?", 
"break the laws of gravity?", 
"start singin' in the rain?", 
"believe what this website tells me?", 
"name all the countries, capitals and presidents in 1 minute?", 
"whisper the answers to my enemies", 
"come clean about my pyramid scheme?",  
"invite you to dinner? Pretty please?", 
"wander in the woods with my wolf?", 
"omit the Oxford comma or does that kill an Oxford person?", 
"rise to the top of my game?", 
"prepare for the worst to come?", 
"develop my uninspired mobile app?",
"test my hypothesis using the unscientific method?", 
"file a noise complaint on my neighbor who makes too little noise?", 
"overstate my skills to give my resume the boost it needs?", 
"play the guitar for 1 month straight to build those calluses?", 
"stop making my terrible puns?", 
"permit dogs in my zoo?", 
"send more memes?", 
"draw a conclusion or a tyrannosaurus?", 
"find a better hobby?",  
"participate in the annual pancake festival in Montpellier?", 
"feel inspired by inspirational quotes?", 
"go touch some grass?", 
"award myself for being so awesome?", 
"charge more for every new HTML form my customer wants?", 
"murder my demons?",
"organize my brain in folders?", 
"realize I'm too old to become a concert ocarinist?", 
"copy Mozart's homework?", 
"speak before I think?", 
"sculpt my marbles or lose my marbles?", 
"ever stop asking questions?", 
"join a brass band on a whim?", 
"Linux as a prank?", 
"sail across the Seven Seas?",  
"swing with a lot of zing?", 
"hide from the crowds of my myriad fans?", 
"approve of the latest Minecraft update?", 
"yell the name of the Scottish play inside an old theater?",
"have a light snack?", 
"lose a bet against myself?", 
"have a sword fight with Daylight saving time?", 
"play the lick?", 
"memorize the entirety of Homer's Iliad and Odyssey?", 
"should I should I... I forgot what I should I.",  
"tell captain Richie to drink less rum?",  
"change this question?"];